# Generated by Django 3.2.13 on 2022-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_club_vs'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_vs',
            name='tarih',
            field=models.BigIntegerField(null=True),
        ),
    ]
